# actions/load-cache-if-exists/action.yml
name: Attempt to Restore Cache
description: Restores the Maven cache from the GitHub Actions cache service.
inputs:
    path:
        description: The path to the Maven cache.
        required: false
        default: $HOME/.m2/repository
    key:
        description: The primary cache key.
        required: false
        #  The glob pattern **/pom.xml will match all pom.xml files in the repository, including the root pom.xml file.
        default: |
            maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
    restore-keys:
        description: Fallback cache keys.
        required: false
        default: |
            ${{ runner.os }}-

#   The key is the primary identifier for a cache. It uniquely defines a cache entry. If the key matches an
#   existing cache entry exactly, that cache will be restored. The default way we use it here is generating
#   based on the inputs or dependencies that define the cache's contents, in our case, the pom files.
#   The restore-keys act as fallback identifiers when an exact match for the key is not found. So, if no
#   cache matches the key, the action searches for partial matches using the restore-keys in the order they
#   are specified. We only have one default here, the runner os and id, but typically, these are
#   progressively broader keys. The idea here is that we want to restore older or more generic caches...
#   which might still be useful if an exact match isn’t available to help speed up the build.

outputs:
    cache-hit:
        description: Indicates whether an exact match was found for the cache key.
        value: ${{ steps.cache-hit.outputs.cache-hit }}

runs:
    using: "composite"
    steps:
        - name: Restore Maven cache
          uses: actions/cache@v4
          with:
              path: ${{ inputs.path }}
              key: ${{ inputs.key }}
              restore-keys: ${{ inputs.restore-keys }}

        - name: Set cache-hit output
          id: cache-hit
          shell: bash
          run: echo "cache-hit=${{ steps.restore-cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
