name: 'Build Module'
description: 'Uses Maven to build the module by name passed in.'

inputs:
  module:
    description: 'Name of module to build.'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Print module name
      shell: bash
      run: echo "Testing module ${{ inputs.module }}"

      # - name: Print source branch name
      #   run: echo "${{ github.ref_name }}"

      # - name: Install Docker
      #   uses: docker/setup-buildx-action@v2
      #   with:
      #     version: 17.09.0-ce

      # - name: Cache Maven dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.m2/repository
      #     key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     distribution: 'temurin'
      #     java-version: '11'

      # - name: Build Maven module
      #   run: mvn clean verify jacoco:report -pl ${{ github.event.inputs.module }} -P JACOCO,CI -e -B \
      #        -Dmaven.repo.local=${{ runner.temp }}/maven_cache -Dmaven.wagon.http.pool=false \
      #        -Dhttp.keepAlive=false -Dstyle.color=always -Djansi.force=true
      #   env:
      #     MAVEN_OPTS: '-Xmx1024m -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss,SSS -Duser.timezone=America/Toronto'

      # - name: Archive test reports
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: '${{ matrix.module }}_test_reports'
      #     path: '**/target/*-reports/*.txt'

      # - name: Publish build artifacts
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: '${{ matrix.module }}_target'
      #     path: '${{ github.workspace }}/${{ matrix.module }}/target/'
